name: 'Compile yaml pipeline'
description: 'Compile yaml pipeline'
inputs:
  toolsdir: 
    description: 'Where to install the tools'
    required: true
    default: ${{ github.workspace }}/bin
  kustomize_version: 
    description: 'kustomize version'
    required: true
    default: 'v3.8.4'
  kubectl_version:
    description: 'kubectl version'
    required: true
    default: 'v1.19.0'
  build:
    default: 'make build'
  publish:
    default: 'make publish'
runs:
  using: 'node12'
  main: 'index.js'