name: 'Compile yaml pipeline'
description: 'Compile yaml pipeline'
inputs:
  program:
    required: true
  registry:
    required: true
  img_name:
    required: true
  maintainer:
    required: true
  owner:
    required: true

runs:
  using: 'node12'
  main: 'index.js'